#!/bin/bash

rm -rf .build

env=local
wcdn=''

while getopts ue: opt
do
  case "$opt" in
    u) wcdn='true'
    ;;
    e) env=$OPTARG
    ;;
  esac
done

export NODE_ENV=$env

if [ "$wcdn" = "true" ]; then
  while true; do
    read -p "Do you really want to upload assets to CDN? (y/n) " yn
    case $yn in
      [Yy]*)
        break
        ;;
      [Nn]*)
        exit
        ;;
      *)
        echo "Please answer yes or no."
        ;;
    esac
  done
fi

mkdir .build
mkdir .build/private
mkdir .build/private/src

cp -r src/ .build/private/src/

node_modules/.bin/ngc -p tsconfig.json
node_modules/.bin/tsc -p tsconfig.json

node_modules/.bin/webpack --config webpack/webpack.polyfills.config.js
node_modules/.bin/webpack --config webpack/webpack.server.config.js
node_modules/.bin/webpack --config webpack/webpack.home.config.js
node_modules/.bin/webpack --config webpack/webpack.contact.config.js

mkdir .build/private/js

mv .build/public/js/server-*.js .build/private/js/server-bundle.js

gulp sass:min

gulp linker:all

if [ "$wcdn" = "true" ]; then
  gulp upload:production
fi

if [ "$NODE_ENV" = "local" ]; then
  node_modules/.bin/nodemon .build/private/js/server-bundle.js
fi
