#!/bin/bash

modulesCount=$(ls -l node_modules | wc -l)

if [ "$modulesCount" -le 1 ]; then
  npm install
fi

rm -rf aot/
rm -rf .build/

node_modules/.bin/ngc -p tsconfig-aot.json
NODE_ENV=production node_modules/.bin/rollup -c rollup-config.js
NODE_ENV=production node_modules/.bin/gulp prod
