#!/bin/bash

modulesCount=$(ls -l node_modules | wc -l)
env=''

if [ "$modulesCount" -le 1 ]; then
  npm install
fi

rm -rf aot/
rm -rf .build/

while getopts ue: opt
do
  case "$opt" in
    u) wcdn='true'
    ;;
    e) env=$OPTARG
    ;;
  esac
done

case "$env" in
  "local" | "development")
    echo "Start environment 'prod'";
    tsc
    gulp local;
    npm start
    ;;
  "-h" | *)
    echo "$0 -e {prod|local}"
esac
