branch-defaults:
  production:
    environment: vador-api
global:
  application_name: vador-api
  default_ec2_keyname: ab-vador
  default_platform: 64bit Amazon Linux 2017.03 v2.7.3 running Docker 17.03.1-ce
  default_region: eu-west-1
  profile: eb-cli
  sc: git
