#!/bin/bash
gulp='node_modules/.bin/gulp'

rm -rf .build

env=local
wcdn=''
watch=''
is_min='false'
is_aot='false'
is_start='false'

while getopts ue:amsw opt
do
  case "$opt" in
    u) wcdn='true'
    ;;
    e) env=$OPTARG
    ;;
    a) is_aot='true'
    ;;
    m) is_min='true'
    ;;
    s) is_start='true'
    ;;
    w) watch='true'
    ;;
  esac
done

export NODE_ENV=$env
export IS_AOT=$is_aot
export IS_MIN=$is_min

if [ "$wcdn" = 'true' ]; then
  while true; do
    read -p 'Do you really want to upload assets to CDN? (y/n) ' yn
    case "$yn" in
      [Yy]*)
        break
        ;;
      [Nn]*)
        exit
        ;;
      *)
        echo 'Please answer yes or no.'
        ;;
    esac
  done
fi

mkdir .build
mkdir .build/private
mkdir .build/public
mkdir .build/private/src

cp -r assets/imgs .build/public/imgs

if [ "$is_min" = 'true' ]; then
  $gulp sass:min
else
  $gulp sass:dev
fi

scripts/ts

if [ "$wcdn" = 'true' ]; then
  $gulp upload:production
fi

if [ "$is_start" = 'true' ]; then
  if [ "$is_min" = 'true' ]; then
    node_modules/.bin/nodemon .build/private/js/server-bundle.js
  elif [ "$watch" = 'true' ]; then
    $gulp serve:local
  else
    node_modules/.bin/nodemon .build/private/src/server/index.js
  fi
fi
